### ISSUE TITLE
All vanilla blocks in creative tab go missing. 1.16.2 With astromine installed

### ISSUE THREAD

**Issue by drakosoldier298** [TeamMidnightDust/Decorative#4] opened 2020-08-26 00:00 UTC
![image](https://user-images.githubusercontent.com/30358222/91239460-2d5ace80-e705-11ea-87bf-41e1588e431a.png)
![image](https://user-images.githubusercontent.com/30358222/91239493-42376200-e705-11ea-8a71-8aac142ebeed.png)

**Comment by ghost** [comment] 2020-08-26 15:10
Energon Relics had a similar incompatibility with Astromine.  Here is how they fixed it: https://gitea.thebrokenrail.com/TheBrokenRail/EnergonRelics/commit/fbb1020ce8bcb35e277d593cadf9452319a1ce7f

**Comment by Motschen** [comment] 2020-09-12 07:38
No real clue how to fix that, also got it when experimenting with Galacticraft Reborn.
I noticed this happened when I changed World Gen in that mod, so I assume its somehow caused by the new Ore Generation.
I looked into the EnergonRelics commit but I didn't really find out which code fixed it.

**Comment by Motschen** [comment] 2020-09-20 18:02
The issue was also present in Delicious Dishes and was fixed in the latest update.
An update to Decorative will follow soon!

**Comment by Motschen** [comment] 2020-10-09 18:55
Fixed in 3.0.0! Sorry for the long time it took, had some real-life stuff going on.

**Closed as completed by Motschen** 2020-10-09 18:55 UTC
Labels: bug
